### ISSUE TITLE
Make the Readme file more descriptive

### ISSUE THREAD

**Issue by arpitjaswal** [arpitjaswal/RescueMeals#1]

**Comment by Anurag-Bharde** [comment]
hello @arpitjaswal It would be a great and very obliging honor for me to contribute to the project, Is it open to be contributed ??

**Comment by Anurag-Bharde** [comment]
could you assign it to me

**Comment by arpitjaswal** [comment]
> could you assign it to me

Please make it nice and descriptive and keep all the original links intact.
